package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"html"
	"io"
	"net/http"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark-meta"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	goldmarkHtml "github.com/yuin/goldmark/renderer/html"

	"github.com/hymkor/goldmark-mb-headingids"
)

//go:embed github.css
var gitHubCss string

const htmlHeader = `<html>
<head>
<style type="text/css"><!--
%s
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}

	@media (max-width: 767px) {
		.markdown-body {
			padding: 15px;
		}
	}
// -->
</style>
</head><body class="markdown-body">`

const htmlFooter = `<hr />
Generated by <a href="https://github.com/hymkor/melw">Melw</a>
Powered by <a href="https://github.com/yuin/goldmark">goldmark</a>
and <a href="https://github.com/sindresorhus/github-markdown-css">github-markdown-css</a>
</body></html>`

var markdownReader goldmark.Markdown

var markdownOptions = []goldmark.Option{
	goldmark.WithParserOptions(
		parser.WithAutoHeadingID()),
	goldmark.WithExtensions(
		extension.Table,
		extension.NewLinkify(
			extension.WithLinkifyAllowedProtocols([][]byte{
				[]byte("http:"),
				[]byte("https:"),
			})),
		extension.TaskList,
		extension.Footnote,
		meta.New(meta.WithTable())),
}

func setMarkdownOptions(enableHtml bool, hardwrap bool) {
	if enableHtml {
		markdownOptions = append(markdownOptions,
			goldmark.WithRendererOptions(goldmarkHtml.WithUnsafe()))
	}
	if hardwrap {
		markdownOptions = append(markdownOptions,
			goldmark.WithRendererOptions(goldmarkHtml.WithHardWraps()))
	}
	markdownReader = goldmark.New(markdownOptions...)
}

func markdownToHtml(source []byte) (io.WriterTo, error) {
	if markdownReader == nil {
		setMarkdownOptions(false, false)
	}
	mdCtx := parser.NewContext(parser.WithIDs(headingids.New()))
	var buffer bytes.Buffer
	err := markdownReader.Convert(source, &buffer, parser.WithContext(mdCtx))
	return &buffer, err
}

func (h *Handler) catAsMarkdown(w http.ResponseWriter, req *http.Request) error {
	source, err := h.ReadFile(req.URL.Path)
	if err != nil {
		return err
	}
	body, err := markdownToHtml(source)
	if err != nil {
		return err
	}
	w.WriteHeader(http.StatusOK)
	w.Header().Add("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, htmlHeader, gitHubCss)
	io.WriteString(w, "<div style=\"float:right\">\n")
	io.WriteString(w, "<a href=\"/\">Index</a>\n")
	io.WriteString(w, "</div>\n")
	fmt.Fprintf(w, "<form method=\"POST\" action=\"%s\">\n",
		html.EscapeString(req.URL.Path))
	io.WriteString(w, "<input type=\"submit\" name=\"a\" value=\"Edit\" />\n")
	io.WriteString(w, "</form>\n")
	body.WriteTo(w)
	fmt.Fprintln(w, htmlFooter)
	return err
}
