package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"html"
	"io"
	"net/http"

	"github.com/yuin/goldmark/v2/extension"
	"github.com/yuin/goldmark/v2/parser"
	goldmarkHTML "github.com/yuin/goldmark/v2/renderer/html"
)

//go:embed github.css
var gitHubCss string

const htmlHeader1 = `<html>
<head>
<style type="text/css"><!--
%s
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}

	@media (max-width: 767px) {
		.markdown-body {
			padding: 15px;
		}
	}
// -->
</style>
</head><body class="markdown-body">`

const htmlHeader2 = `<html>
<head>
<style type="text/css"><!--
%s
.markdown-body {
	box-sizing: border-box;
	min-width: 200px;
	// max-width: 980px;
	margin: 0 auto;
	padding: 10px;
}

@media (max-width: 767px) {
	.markdown-body {
		padding: 15px;
	}
}

.editor {
	display: grid;
	grid-template-columns: 1fr 1fr;
	height: 100vh;
}

.editor-pane {
	display: grid;
	grid-template-rows: auto minmax(0, 1fr) auto;
	min-width: 0;
	min-height: 0;
	padding: 10px;
}

.editor-pane textarea {
	width: 100%%;
	height: 100%%;
	box-sizing: border-box;
	min-height: 0;
}

.buttons {
	padding: 0.5em;
}

.preview-pane {
	overflow: auto;
	padding: 10px;
}

// -->
</style>
<script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js"></script>
</head><body class="markdown-body">`

const copyright = `<hr />
Generated by <a href="https://github.com/hymkor/melw">Melw</a>
Powered by <a href="https://github.com/yuin/goldmark">goldmark</a>
and <a href="https://github.com/sindresorhus/github-markdown-css">github-markdown-css</a>
`

const htmlFooter = copyright + "</body></html>"

var (
	markdownParser   parser.Parser
	markdownRenderer goldmarkHTML.Renderer
)

func setMarkdownOptions(enableHTML bool, hardwrap bool) {
	parserOptions := []parser.Option{
		parser.WithAutoHeadingID(),
		parser.WithExtensions(
			extension.NewTableParser(),
			extension.NewLinkifyParser(
				extension.WithAllowedProtocols(
					[]string{"http:", "https:"},
				),
			),
			extension.NewTaskListItemParser(),
			extension.NewFootnoteParser(),
			extension.NewStrikethroughParser(),
		),
	}

	rendererOptions := []goldmarkHTML.Option{
		goldmarkHTML.WithExtensions(
			extension.TableHTMLRenderer,
			extension.TaskListItemHTMLRenderer,
			extension.FootnoteHTMLRenderer,
			extension.StrikethroughHTMLRenderer,
		),
	}

	if enableHTML {
		rendererOptions = append(rendererOptions, goldmarkHTML.WithUnsafe())
	}
	if hardwrap {
		rendererOptions = append(rendererOptions, goldmarkHTML.WithHardWraps())
	}

	markdownParser = parser.New(parserOptions...)
	markdownRenderer = goldmarkHTML.New(rendererOptions...)
}

func markdownToHtml(source []byte) (io.WriterTo, error) {
	if markdownParser == nil {
		setMarkdownOptions(false, false)
	}
	var buffer bytes.Buffer
	doc := markdownParser.Parse(source)
	err := markdownRenderer.Render(&buffer, source, doc)
	return &buffer, err
}

func (h *Handler) serveMarkdown(w http.ResponseWriter, req *http.Request) error {
	source, err := h.ReadFile(req.URL.Path)
	if err != nil {
		return err
	}
	body, err := markdownToHtml(source)
	if err != nil {
		return err
	}
	showOK(w)
	fmt.Fprintf(w, htmlHeader1, gitHubCss)
	io.WriteString(w, "<div style=\"float:right\">\n")
	printNestPath(w, req.URL.Path)
	io.WriteString(w, "</div>\n")
	fmt.Fprintf(w, "<form method=\"POST\" action=\"%s\">\n",
		html.EscapeString(req.URL.Path))
	io.WriteString(w, "<input type=\"submit\" name=\"a\" value=\"Edit\" />\n")
	io.WriteString(w, "</form>\n")
	body.WriteTo(w)
	fmt.Fprintln(w, htmlFooter)
	return err
}
